Fix AttributeError: 'unicode' object has no attribute 'items'
When the messages types between the ROS and json have a mismatch, a
AttributeError could be thrown. Let's convert this try block to catch
all exceptions, because the bridge should just continue running in that
case.